services:
  proof-server:
    image: "ghcr.io/midnight-ntwrk/proof-server:${PROOF_SERVER_VERSION}"
    container_name: "proof-server_$TESTCONTAINERS_UID"
    command: [ 'midnight-proof-server --verbose' ]
    ports:
      - "0:6300"
    environment:
      EXTRA_ARGS: -v
      RUST_BACKTRACE: "full"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6300/version" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
