#!/usr/bin/env bash

# This file is part of midnight-js.
# Copyright (C) 2025-2026 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Docker-host equivalent of build-compactc.sh — builds the image that
# delegates to build-compactc.sh internally, then writes a host wrapper that
# proxies each invocation into the image. Slower per-call than nix-on-host
# (~1-2s Docker startup overhead each compactc invocation on macOS).

set -euo pipefail

# shellcheck source=./lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$REPO_ROOT"

assert_submodule_initialized
assert_command docker "building compactc without host nix"

home="${REPO_ROOT}/.compact-home"
mkdir -p "$home"

image_tag="midnight-js-compactc-local:latest"
echo "Building compactc Docker image '$image_tag' (first build can be slow)..."

# Build context = repo root, narrowed by the repo-root `.dockerignore` to
# `scripts/` and `compact/` (minus compact/.git). The Dockerfile invokes the
# same scripts/build-compactc.sh we use for native nix builds, so the
# extraction logic and wrapper layout live in one place.
#
# The compactc bundle is installed at /compactc-home (NOT /work/.compact-home)
# so the runtime bind-mount of the caller's CWD to /host-cwd cannot shadow it.
docker build --tag "$image_tag" --file - "$REPO_ROOT" <<'DOCKERFILE'
FROM nixos/nix:latest
# sandbox=false: container runtimes usually lack user namespaces nix needs.
RUN mkdir -p /etc/nix && { \
    echo "extra-experimental-features = nix-command flakes"; \
    echo "sandbox = false"; \
    echo "extra-substituters = https://cache.iog.io"; \
    echo "extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="; \
  } >> /etc/nix/nix.conf
COPY scripts/build-compactc.sh /opt/build-compactc/scripts/build-compactc.sh
COPY scripts/lib.sh /opt/build-compactc/scripts/lib.sh
COPY compact /opt/build-compactc/compact
WORKDIR /opt/build-compactc
# `path:` flake ref tolerates the missing `.git` (excluded by .dockerignore).
ENV COMPACTC_FLAKE_REF=path:/opt/build-compactc/compact
# Direct the script to lay the bundle outside the host bind-mount target.
ENV COMPACT_BUILD_OUT=/compactc-home
RUN /opt/build-compactc/scripts/build-compactc.sh
ENTRYPOINT ["/compactc-home/compactc"]
DOCKERFILE

# Host wrapper. run-compactc invokes `$COMPACT_HOME/compactc <args>` where
# args are paths relative to the package's CWD. Mount that CWD at /host-cwd
# and run the container with --workdir /host-cwd so relative paths resolve.
# --user keeps generated files owned by the host user (not root). Stage to
# a sibling .new + mv so an interrupted write cannot leave the wrapper
# unexecutable (or empty).
image_tag_q=$(printf '%q' "$image_tag")
cat > "$home/compactc.new" <<EOF
#!/usr/bin/env bash
# Generated by scripts/build-compactc-docker.sh — do not edit.
exec docker run --rm \\
  --user "\$(id -u):\$(id -g)" \\
  --volume "\$PWD:/host-cwd" \\
  --workdir /host-cwd \\
  ${image_tag_q} "\$@"
EOF
chmod +x "$home/compactc.new"
mv "$home/compactc.new" "$home/compactc"

echo "compactc Docker wrapper ready at $home/compactc"
echo "COMPACT_HOME=$home (.envrc auto-exports it after direnv reload)"
