#!/usr/bin/env bash

# This file is part of midnight-js.
# Copyright (C) 2025-2026 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build compactc from the `compact/` submodule via nix; write a COMPACT_HOME
# wrapper that bakes version-locked zkir/zkir-v3 onto PATH (preventing
# silent proving-key incompatibility from a stray zkir) and registers a
# nix-gcroot so the build survives `nix-collect-garbage`.

set -euo pipefail

# shellcheck source=./lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$REPO_ROOT"

assert_submodule_initialized
assert_command nix "building compactc from the submodule"

# Output directory for the wrapper + nix gcroot. Defaults to `.compact-home`
# at the repo root; `scripts/build-compactc-docker.sh` overrides it via
# COMPACT_BUILD_OUT to install the bundle outside its runtime bind-mount target.
home="${COMPACT_BUILD_OUT:-${REPO_ROOT}/.compact-home}"
mkdir -p "$home"

# Default flake reference: `path:` works with paths containing spaces and
# without a `.git` (unlike `git+file://`). Overridable via COMPACTC_FLAKE_REF.
flake_ref="${COMPACTC_FLAKE_REF:-$(default_compact_flake_ref)}"

# --out-link registers an indirect gcroot, so the built compiler survives
# `nix-collect-garbage` and the wrapper keeps pointing at a live store path.
echo "Building compactc from ${flake_ref} (first build can be slow)..."
nix build --out-link "$home/result" "${flake_ref}#compactc-binary"

# Bash-escape $home before embedding into the generated wrapper so a path
# containing `$`, backticks, or other metacharacters cannot corrupt (or inject
# into) the wrapper at write time. The trailing `\$PATH`/`\$@` keep PATH and
# arguments unexpanded until the wrapper actually runs.
home_q=$(printf '%q' "$home")
cat > "$home/compactc" <<EOF
#!/usr/bin/env bash
# Generated by scripts/build-compactc.sh — do not edit.
export PATH=${home_q}/result/lib:\$PATH
exec ${home_q}/result/bin/compactc.bin "\$@"
EOF
chmod +x "$home/compactc"

actual_version=$("$home/compactc" --version)
echo "compactc ${actual_version} ready"
echo "COMPACT_HOME=${home} (exported automatically in the dev shell / direnv)"

# Warn (but don't fail) when the built compactc and .envrc's COMPACTC_VERSION
# disagree — source-builds against a feature branch legitimately drift, but a
# silent mismatch hides real config errors (e.g. forgetting to bump
# COMPACTC_VERSION after a submodule bump). Substring match handles both bare
# version strings ("0.31.0") and decorated forms ("compactc 0.31.0").
if [ -n "${COMPACTC_VERSION:-}" ] && [[ "$actual_version" != *"$COMPACTC_VERSION"* ]]; then
  echo "warning: built compactc reports '${actual_version}' but COMPACTC_VERSION='${COMPACTC_VERSION}'." >&2
  echo "         Bump .envrc's COMPACTC_VERSION or the compact/ submodule to align them." >&2
fi
