name: CI
env:
  MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

permissions:
  contents: read
  issues: read
  id-token: write
  packages: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      build_shared: ${{ steps.build-targets.outputs.shared }}
      build_mn_js: ${{ steps.build-targets.outputs.midnight-js }}
      build_t_js: ${{ steps.build-targets.outputs.testkit-js }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6.4.0
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@midnight-ntwrk'
          node-version-file: '.nvmrc'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Determine Build Targets
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # ratchet:dorny/paths-filter@v4.0.1
        id: build-targets
        with:
          filters: |
            shared:
              - '.github/workflows/**'
              - 'yarn.lock'
              - 'package.json'
            midnight-js:
              - 'packages/**'
            testkit-js:
              - 'packages/**'
              - 'testkit-js/**'

  ci-midnightjs:
    needs: ci
    name: Build Midnight.js
    uses: ./.github/workflows/ci-midnight-js.yml
    with:
      should_run: ${{ needs.ci.outputs.build_mn_js == 'true' || needs.ci.outputs.build_shared == 'true' }}
      should_prerelease: ${{
          github.event_name != 'schedule' &&
          (github.ref_name == 'main' || contains(github.event.head_commit.message, '[do_publish]') || github.event_name == 'workflow_dispatch')
        }}
    secrets: inherit

  ci-testkit:
    needs: ci
    name: Build Testkit.js
    with:
      should_run: ${{ needs.ci.outputs.build_t_js == 'true' || needs.ci.outputs.build_shared == 'true' }}
      should_prerelease: ${{
          github.event_name != 'schedule' &&
          (github.ref_name == 'main' || contains(github.event.head_commit.message, '[do_publish]') || github.event_name == 'workflow_dispatch')
        }}
      network: undeployed
    uses: ./.github/workflows/ci-testkit-js.yml
    secrets: inherit
