name: Publish updated API documentation

permissions:
  contents: write
  pull-requests: write

env:
  MIDNIGHTBOT_PACKAGES_WRITE: ${{ secrets.MIDNIGHTBOT_PACKAGES_WRITE }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

      - name: Setup api.github.com credentials
        uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # ratchet:extractions/netrc@v3
        with:
          machine: api.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Setup github.com credentials
        uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # ratchet:extractions/netrc@v3
        with:
          machine: github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0

      - name: Install direnv
        run: curl -sfL https://direnv.net/install.sh | DIRENV_GITHUB_API_TOKEN=$GITHUB_TOKEN  bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load environment from .envrc
        run: |
          direnv allow .
          direnv export gha >> "$GITHUB_ENV"

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6.4.0
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@midnight-ntwrk'
          node-version-file: '.nvmrc'
          cache: 'yarn'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTBOT_PACKAGES_WRITE }}

      - name: Cache Turbo and Yarn dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # ratchet:actions/cache@v6.1.0
        with:
          path: |
            **/node_modules
            ~/.yarn
            .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/turbo.json') }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Configure yarn
        run: yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "$MIDNIGHTBOT_PACKAGES_WRITE"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the project
        run: yarn build --cache-dir ./turbo
        env:
          GITHUB_TOKEN: ${{ secrets.MIDNIGHTBOT_PACKAGES_WRITE }}

      - name: Generate documentation (midnight-js and testkit-js)
        run: |
          yarn run build:markdown-docs
          cd testkit-js/testkit-js && yarn run build:markdown-docs

      - name: Check if there are changes in docs and create a new branch
        id: set_update
        run: |
          if [ -n "$(git status ./docs --porcelain)" ]; then
            echo "Adding new..."
            git config --global user.email "midnight-ci@users.noreply.github.com"
            git config --global user.name "Midnight CI GitHub Action"
            BRANCH=api-docs/merge-prs/`date +'%Y-%m-%dT%H%M%S'`
            git checkout -b $BRANCH
            git remote set-url origin "https://$GH_TOKEN@github.com/${{ github.repository }}.git"
            git push -u origin $BRANCH
            echo "UPDATE=true" >> $GITHUB_OUTPUT
            echo "NEW_BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "Nothing to update"
            echo "UPDATE=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: MonikaJassova/ghcommit-action@aee0efc02d3707e178c534477e5c87f70fe6678f
        if: steps.set_update.outputs.UPDATE == 'true'
        with:
          commit_message: "docs: API documentation update"
          repo: ${{ github.repository }}
          branch: ${{ steps.set_update.outputs.NEW_BRANCH }}
          file_pattern: 'docs *.md'
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Open a PR
        if: steps.set_update.outputs.UPDATE == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NEW_BRANCH: ${{ steps.set_update.outputs.NEW_BRANCH }}
        run: |
          gh pr create --base main --head "$NEW_BRANCH" --title "docs: API documentation update" --body "Update API documentation - created by Midnight CI Github Action"
